In [115]:
import pandas as pd
from pandas import DataFrame
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as ptr
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn import svm
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [52]:
#importing the digits DataSet

digit_data= datasets.load_digits()

digits=DataFrame(data= digit_data.data, columns= digit_data.feature_names)
digits['target']= digit_data.target

t= digits['target']
del digits['target']

digits.head(5)



pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0        0.0        0.0        5.0       13.0        9.0        1.0   
1        0.0        0.0        0.0       12.0       13.0        5.0   
2        0.0        0.0        0.0        4.0       15.0       12.0   
3        0.0        0.0        7.0       15.0       13.0        1.0   
4        0.0        0.0        0.0        1.0       11.0        0.0   

   pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1        0.0        0.0        0.0        0.0  ...        0.0        0.0   
2        0.0        0.0        0.0        0.0  ...        5.0        0.0   
3        0.0        0.0        0.0        8.0  ...        9.0        0.0   
4        0.0        0.0        0.0        0.0  ...        0.0        0.0   

   pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0        0.0        0.0        6.0       13.0       10.0        0.0   
1        0.0        0.0        0.0       11.0       16.0       10.0   
2        0.0        0.0        0.0        3.0       11.0       16.0   
3        0.0        0.0        7.0       13.0       13.0        9.0   
4        0.0        0.0        0.0        2.0       16.0        4.0   

   pixel_7_6  pixel_7_7  
0        0.0        0.0  
1        0.0        0.0  
2        9.0        0.0  
3        0.0        0.0  
4        0.0        0.0  

[5 rows x 64 columns]

In [53]:
# #make train and test data sets
# train_x, test_x, train_y, test_y= train_test_split(digits, t, train_size=0.8, random_state=3)

# #make a general function for getting score
# def get_score(model, train_x, test_x, train_y, test_y):
#     model.fit(train_x, train_y)
#     return model.score(test_x, test_y)


In [54]:

#get_score(svm.SVC(), train_x, test_x, train_y, test_y)

In [108]:
kf= KFold()

score_l= []
score_svm= []

for train_index, test_index in kf.split(digits):
    train_x, test_x, train_y, test_y= digit_data.data[train_index], digit_data.data[test_index], digit_data.target[train_index], digit_data.target[test_index]
    score_l.append(get_score(LogisticRegression(max_iter= 5000), train_x, test_x, train_y, test_y))
    score_svm.append(get_score(svm.SVC(), train_x, test_x, train_y, test_y))

score_l


[0.9305555555555556,
 0.8777777777777778,
 0.9415041782729805,
 0.9387186629526463,
 0.8997214484679665]

In [95]:
def average(arr):
    n= len(arr)
    Sum= 0
    for i in arr:
        Sum= Sum + i
    return Sum/n    

In [96]:
average(score_i)

0.9176555246053854

In [98]:
average(score_svm)

0.9660631383472609

In [101]:
score_svm

[0.9694444444444444,
 0.9472222222222222,
 0.9832869080779945,
 0.9888579387186629,
 0.9415041782729805]

In [113]:
cross_val_score(LogisticRegression(max_iter= 5000), digits, t, cv= 3)

array([0.92487479, 0.93823038, 0.92320534])

In [119]:
cross_val_score(svm.SVC(C= 30), digits, t, cv= 3)

array([0.96828047, 0.97996661, 0.97328881])

In [117]:
cross_val_score(RandomForestClassifier(n_estimators= 30), digits, t, cv= 3)

array([0.92153589, 0.94824708, 0.92988314])